services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "dummyuser"
      POSTGRES_PASSWORD: "dummypassword"
      POSTGRES_DB: "testdb_01"
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
  db-access:
    image: oven/bun:alpine
    restart: always
    working_dir: /app
    command: ["bun", "run", "dev"]
    develop:
      watch:
        - action: restart
          path: ./postgresql-db/
        - action: restart
          path: ./compose.yaml
    environment:
      HTTP_PORT: 4002
      POSTGRES_HOST: "db"
      AUTH_JWT_SECRET: "dev-insecure-secret-change-me"
    ports:
      - 4002:4002
    networks:
      - default
    volumes:
      - ./postgresql-db:/app
    healthcheck:
      test: ["CMD-SHELL", "bun run scripts/healthcheck.ts"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 5s
    depends_on:
      db:
        condition: service_healthy
  graphql:
    image: oven/bun:alpine
    restart: always
    # dev mode for now, later will make separate compose files
    working_dir: /app
    command: ["bun", "run", "dev"]
    develop:
      watch:
        - action: restart
          path: ./graphql-api/
        - action: restart
          path: ./compose.yaml
    environment:
      HTTP_PORT: 4001
      RECIPES_API_ENDPOINT: "http://db-access:4002"
      AUTH_JWT_SECRET: "dev-insecure-secret-change-me"
    ports:
      - 4001:4001
    networks:
      - default
    volumes:
      - ./graphql-api:/app
    healthcheck:
      test: ["CMD-SHELL", "bun run scripts/healthcheck.ts"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    depends_on:
      db-access:
        condition: service_healthy
  client-ui:
    image: oven/bun:latest
    build:
      context: ./client-ui
    restart: always
    develop:
      watch:
        # - action: restart
        #   path: ./client-ui/
        - action: restart
          path: ./compose.yaml
    environment:
      HTTP_PORT: 4000
      GRAPHQL_API_ENDPOINT: "http://graphql:4001/graphql"
      DB_ACCESS_ENDPOINT: "http://db-access:4002"
    command: ["./dev.sh"]
    ports:
      - 4000:4000
    networks:
      - default
    volumes:
      - ./client-ui:/app
    depends_on:
      graphql:
        condition: service_healthy
volumes:
  db-data:
